- hosts: rancher
  gather_facts: False
  tasks: 
    - name: install python-docker
      shell: pip3 install docker-py

    - name: start daemon docker
      service: 
        name: docker
        state: started

    - name: launch rancher
      community.docker.docker_container:
        name: rancher
        state: started
        image: 2.3.3
        pull: true
        privileged: yes
        restart_policy: unless-stopped
        ports:
          - "8080:80"
          - "8443:443"
        volumes:
          - "/host/rancher:/var/lib/rancher"
      vars:
        ansible_python_interpreter: /bin/python3